import { Button, Center, Container, Stack, Text } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import {
  LinkIcon,
  PhotoIcon,
  CodeBracketIcon,
} from "@heroicons/react/24/outline";
import { SVGProps } from "react";
import Link from "next/link";
type Props = {
  text: String;
  icon: JSX.Element;
  url: String;
};
const NewLinkComponent = ({ text, icon, url }: Props) => {
  return (
    //@ts-ignore
    <Link href={url}>
      <div className="shadow-sm rounded-md hover:shadow-xl font-bold relative  hover:bg-gray-100 p-6 flex justify-center items-center transition-all ease-out duration-200 hover:cursor-pointer active:scale-90">
        <Text size="xl" className="flex-1 flex justify-center items-center">
          {text}
        </Text>
        {icon}
      </div>
    </Link>
  );
};

const NewPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center style={{ height: "100vh", width: "100vw" }}>
        <Stack spacing="xl" style={{ width: "350px" }}>
          <NewLinkComponent
            text="New Shortened Link"
            icon={<LinkIcon className="ml-2 h-6 w-6 absolute right-5" />}
            url="/link/new"
          />

          <NewLinkComponent
            text="New Image Link"
            icon={<PhotoIcon className="ml-2 h-6 w-6 absolute right-5" />}
            url="/image/new"
          />
          <NewLinkComponent
            text="New JSON Link"
            icon={<CodeBracketIcon className="ml-2 h-6 w-6 absolute right-5" />}
            url="/json/new"
          />
        </Stack>
      </Center>
    </div>
  );
};

export default NewPage;
